# Generated by Django 3.1.7 on 2021-04-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название препарата')),
                ('description', models.TextField(verbose_name='Описание препарата')),
                ('dose', models.CharField(default='', max_length=255, verbose_name='Дозировка препарата')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата его назначения')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='Время его назначения')),
                ('finish_date', models.DateField(auto_now_add=True, verbose_name='Дата окончания приёма')),
            ],
        ),
    ]
