# Generated by Django 3.1.7 on 2021-04-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.IntegerField(verbose_name='Пациент')),
                ('doctor', models.IntegerField(verbose_name='Пациент')),
                ('medrecord', models.IntegerField(verbose_name='Мед. карточка')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок тренировки')),
                ('descrption', models.TextField(verbose_name='Описание тренировки')),
                ('finish_date', models.DateField(verbose_name='Дата окончание тренировок')),
            ],
        ),
    ]
