# Generated by Django 3.1.2 on 2021-01-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.IntegerField(verbose_name='ID пациента')),
                ('doctor', models.IntegerField(verbose_name='ID врача')),
                ('diagnosis', models.CharField(default='Не определён', max_length=255, verbose_name='Диагноз')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
