# Generated by Django 3.1.2 on 2021-01-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medrecords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medrecord',
            name='training_list',
            field=models.TextField(default='{}', verbose_name='Списко тренеровок(JSON)'),
        ),
    ]
