# Generated by Django 3.1.2 on 2021-01-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medrecords', '0002_medrecord_training_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='medrecord',
            name='active_id',
            field=models.IntegerField(default=0, verbose_name='ID актуального врача'),
        ),
    ]
