# Generated by Django 3.1.5 on 2021-01-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medrecords', '0004_auto_20210116_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medrecord',
            name='training_list',
            field=models.TextField(default='[]', verbose_name='Списко тренеровок(JSON)'),
        ),
    ]
