# Generated by Django 3.1.7 on 2021-04-07 20:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medrecords', '0016_auto_20210407_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medrecord',
            name='medications',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=['arr'], size=None),
        ),
    ]
