# Generated by Django 3.1.7 on 2021-04-14 20:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medrecords', '0020_auto_20210407_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medrecord',
            name='medications',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
    ]
