# Generated by Django 3.1.7 on 2021-04-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medrecords', '0021_auto_20210414_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medrecord',
            name='active_id',
            field=models.IntegerField(default=1, verbose_name='ID актуального врача'),
        ),
    ]
