# Generated by Django 3.1.2 on 2020-11-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='00000000', max_length=255, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='00000000', max_length=255, verbose_name='Фамилия'),
        ),
    ]
