# Generated by Django 3.1.2 on 2020-12-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201121_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='static/upload_files/default_user.png', upload_to='static/upload_files', verbose_name='Аватар пользователя'),
        ),
    ]
