# Generated by Django 3.1.2 on 2020-12-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(default='Пациент', max_length=255, verbose_name='Тип пользователя'),
        ),
    ]
