# Generated by Django 3.1.7 on 2021-04-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialist',
            field=models.CharField(default='none', max_length=255, verbose_name='Специальность'),
        ),
    ]
