# Generated by Django 3.1.7 on 2021-05-15 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('code', models.CharField(max_length=255)),
                ('created', models.DateTimeField(default=datetime.datetime(2021, 5, 15, 17, 14, 17, 284896))),
            ],
        ),
    ]
