# Generated by Django 3.1.7 on 2021-05-15 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_tg_code', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 15, 17, 19, 47, 176687)),
        ),
    ]
