# Generated by Django 3.1.7 on 2021-05-15 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_tg_code', '0002_auto_20210515_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='code',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 15, 20, 5, 14, 299597)),
        ),
    ]
