# Generated by Django 3.1.2 on 2021-01-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientFirstName', models.CharField(max_length=255)),
                ('patientLastName', models.CharField(max_length=255)),
                ('created', models.DateField(auto_now=True)),
                ('dateEvent', models.DateField()),
                ('timeEvent', models.TimeField()),
                ('doctor', models.IntegerField()),
                ('patient', models.IntegerField(default=0)),
            ],
        ),
    ]
