# Generated by Django 3.1.2 on 2021-01-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='status',
            field=models.CharField(default='в ожидании', max_length=255),
        ),
        migrations.AlterField(
            model_name='record',
            name='patient',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
