# Generated by Django 3.1.5 on 2021-01-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20210117_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='patientNumberPhone',
            field=models.CharField(default='', max_length=255),
        ),
    ]
