# Generated by Django 3.1.5 on 2021-01-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_record_patientnumberphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='patientFirstName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='patientLastName',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
